title: "Jason Winn" # the name of your site, e.g. ACME Corp.
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/new_site" # the subpath of your site, e.g. /blog
url: "jasonwinn.ca" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  - work_items
  - hobby_items
defaults:
- scope:
    path: "assets/img"
  values:
    image: true